baseURL = 'https://asimov.top/'
languageCode = 'en-us'
title = 'Asimov Ai'
theme = 'typo'

[module]
  [[module.imports]]
    path = "github.com/divinerites/plausible-hugo"

[params.plausible]
  # (必须) 设置为 true 来启用脚本
  enable = true
  # (必须) 填写你被追踪的网站域名 (不是你Plausible的地址)
  domain = "asimov.top"
  # 自托管 Plausible
  selfhosted_domain="plausible.asimov.top"

  # --- 以下是可选测量功能的开关 ---
  
  # 跟踪出站链接点击
  outboundLinks = true 
  # 跟踪文件下载
  fileDownloads = false
  # 跟踪404页面 (需要你的404页面也加载了此脚本)
  notFound = false
  # 适用于SPA应用的哈希路由模式
  hashBased = false
  # 启用自定义事件跟踪 (需要你手动在JS中调用 `plausible('event')`)
  customEvents = true

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Asimov's Personal Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi there ~'
homeIntroContent = """
Nice to meet you here :) &nbsp;&nbsp; My name is Asimov. <br>
I'm a software developer and I've been building things for years. I absolutely love playing around with new tools and tech, and love to using them to make life easier. <br>
**I am currently looking for job opportunities. If you know of any roles in Auckland (or remote positions from anywhere in the world), I’d truly appreciate a recommendation.** <br>
Feel free to read [about myself](/about/) or to look at my [projects](/projects) and my [posts](/posts/).
[![Asimov's GitHub stats](https://github-readme-stats-six-navy-14.vercel.app/api?username=aizhimou&show_icons=true&theme=transparent&hide=contribs,prs)](https://github.com/aizhimou)
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/aizhimou"

[[params.social]]
name = "x"
url = "https://x.com/aizhimoug"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/%E5%BF%97%E8%B0%8B-%E8%89%BE-667bb22b9/"


# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "projects"
url = "/projects"

# [[params.menu]]
# name = "speeches"
# url = "/speeches"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
