backend:
  name: github
  repo: aizhimou/my-blog 
  branch: main 
  # base_url: https://my-hugo-blog-auth-proxy-bqr5s506d-aizhimous-projects.vercel.app
  base_url: https://decap-proxy.asimov.workers.dev
  auth_endpoint: api/auth
  auth_scope: repo

media_folder: 'static/uploads' # 全局默认的媒体文件夹
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}/index'
    media_folder: 'content/posts/{{slug}}' 
    public_folder: '{{slug}}'

    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Toc', name: 'toc', widget: "boolean", default: true }
      - { label: 'Autonumber', name: 'autonumber', widget: "boolean", default: false }
      - { label: 'Math', name: 'math', widget: "boolean", default: true }
      - { label: 'ShowTags', name: 'showTags', widget: "boolean", default: true }
      - { label: 'Tags', name: 'tags', widget: "list" }
      - { label: 'Body', name: 'body', widget: 'markdown' }