backend:
  name: github
  repo: aizhimou/my-blog 
  branch: main 
  base_url: https://my-hugo-blog-auth-proxy-bqr5s506d-aizhimous-projects.vercel.app
  auth_endpoint: api/auth
  auth_scope: repo,user

# media_folder: static/img
# public_folder: /img

collections:
  - name: 'posts'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}/index'
    media_folder: 'content/posts/{{slug}}' 
    public_folder: '{{slug}}'

    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }